set_location_assignment PIN_Y2 -to clk
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to clk

set_location_assignment PIN_M23 -to reset_n
set_instance_assignment -name IO_STANDARD "2.5 V" -to reset_n

#============================================================
# KEYS
#============================================================
set_location_assignment PIN_M21 -to KEYS[0]
set_location_assignment PIN_N21 -to KEYS[1]
set_location_assignment PIN_R24 -to KEYS[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to KEYS[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to KEYS[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to KEYS[2]

#============================================================
# SEVEN SEGMENT DISPLAYS
#============================================================
set_location_assignment PIN_G18 -to sev_seg_0[0]
set_location_assignment PIN_F22 -to sev_seg_0[1]
set_location_assignment PIN_E17 -to sev_seg_0[2]
set_location_assignment PIN_L26 -to sev_seg_0[3]
set_location_assignment PIN_L25 -to sev_seg_0[4]
set_location_assignment PIN_J22 -to sev_seg_0[5]
set_location_assignment PIN_H22 -to sev_seg_0[6]    

set_location_assignment PIN_M24 -to sev_seg_1[0]
set_location_assignment PIN_Y22 -to sev_seg_1[1]
set_location_assignment PIN_W21 -to sev_seg_1[2]
set_location_assignment PIN_W22 -to sev_seg_1[3]
set_location_assignment PIN_W25 -to sev_seg_1[4]
set_location_assignment PIN_U23 -to sev_seg_1[5]
set_location_assignment PIN_U24 -to sev_seg_1[6] 

set_location_assignment PIN_AA25 -to sev_seg_2[0]
set_location_assignment PIN_AA26 -to sev_seg_2[1]
set_location_assignment PIN_Y25 -to sev_seg_2[2]
set_location_assignment PIN_W26 -to sev_seg_2[3]
set_location_assignment PIN_Y26 -to sev_seg_2[4]
set_location_assignment PIN_W27 -to sev_seg_2[5]
set_location_assignment PIN_W28 -to sev_seg_2[6] 

set_location_assignment PIN_V21 -to sev_seg_3[0]
set_location_assignment PIN_U21 -to sev_seg_3[1]
set_location_assignment PIN_AB20 -to sev_seg_3[2]
set_location_assignment PIN_AA21 -to sev_seg_3[3]
set_location_assignment PIN_AD24 -to sev_seg_3[4]
set_location_assignment PIN_AF23 -to sev_seg_3[5]
set_location_assignment PIN_Y19 -to sev_seg_3[6] 

set_location_assignment PIN_AB19 -to sev_seg_4[0]
set_location_assignment PIN_AA19 -to sev_seg_4[1]
set_location_assignment PIN_AG21 -to sev_seg_4[2]
set_location_assignment PIN_AH21 -to sev_seg_4[3]
set_location_assignment PIN_AE19 -to sev_seg_4[4]
set_location_assignment PIN_AF19 -to sev_seg_4[5]
set_location_assignment PIN_AE18 -to sev_seg_4[6] 

set_location_assignment PIN_AD18 -to sev_seg_5[0]
set_location_assignment PIN_AC18 -to sev_seg_5[1]
set_location_assignment PIN_AB18 -to sev_seg_5[2]
set_location_assignment PIN_AH19 -to sev_seg_5[3]
set_location_assignment PIN_AG19 -to sev_seg_5[4]
set_location_assignment PIN_AF18 -to sev_seg_5[5]
set_location_assignment PIN_AH18 -to sev_seg_5[6] 

set_location_assignment PIN_AA17 -to sev_seg_6[0]
set_location_assignment PIN_AB16 -to sev_seg_6[1]
set_location_assignment PIN_AA16 -to sev_seg_6[2]
set_location_assignment PIN_AB17 -to sev_seg_6[3]
set_location_assignment PIN_AB15 -to sev_seg_6[4]
set_location_assignment PIN_AA15 -to sev_seg_6[5]
set_location_assignment PIN_AC17 -to sev_seg_6[6] 

set_location_assignment PIN_AD17 -to sev_seg_7[0]
set_location_assignment PIN_AE17 -to sev_seg_7[1]
set_location_assignment PIN_AG17 -to sev_seg_7[2]
set_location_assignment PIN_AH17 -to sev_seg_7[3]
set_location_assignment PIN_AF17 -to sev_seg_7[4]
set_location_assignment PIN_AG18 -to sev_seg_7[5]
set_location_assignment PIN_AA14 -to sev_seg_7[6] 

#============================================================
# GREEN LEDS
#============================================================
set_location_assignment PIN_E21 -to LEDG[0]
set_location_assignment PIN_E22 -to LEDG[1]
set_location_assignment PIN_E25 -to LEDG[2]
set_location_assignment PIN_E24 -to LEDG[3]
set_location_assignment PIN_H21 -to LEDG[4]
set_location_assignment PIN_G20 -to LEDG[5]
set_location_assignment PIN_G22 -to LEDG[6]
set_location_assignment PIN_G21 -to LEDG[7]
set_location_assignment PIN_F17 -to LEDG[8]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[7]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDG[8]

#============================================================
# RED LEDS
#============================================================
set_location_assignment PIN_G19 -to LEDR[0]
set_location_assignment PIN_E19 -to LEDR[2]
set_location_assignment PIN_F19 -to LEDR[1]
set_location_assignment PIN_F21 -to LEDR[3]
set_location_assignment PIN_F18 -to LEDR[4]
set_location_assignment PIN_E18 -to LEDR[5]
set_location_assignment PIN_J19 -to LEDR[6]
set_location_assignment PIN_H19 -to LEDR[7]
set_location_assignment PIN_J17 -to LEDR[8]
set_location_assignment PIN_G17 -to LEDR[9]
set_location_assignment PIN_J15 -to LEDR[10]
set_location_assignment PIN_H16 -to LEDR[11]
set_location_assignment PIN_J16 -to LEDR[12]
set_location_assignment PIN_H17 -to LEDR[13]
set_location_assignment PIN_F15 -to LEDR[14]
set_location_assignment PIN_G15 -to LEDR[15]
set_location_assignment PIN_G16 -to LEDR[16]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[7]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[8]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[9]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[10]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[11]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[12]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[13]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[14]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[15]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LEDR[16]

#============================================================
# SWITCHES
#============================================================
set_location_assignment PIN_AB28 -to switches[0]
set_location_assignment PIN_AC28 -to switches[1] 
set_location_assignment PIN_AC27 -to switches[2]
set_location_assignment PIN_AD27 -to switches[3]
set_location_assignment PIN_AB27 -to switches[4]
set_location_assignment PIN_AC26 -to switches[5]
set_location_assignment PIN_AD26 -to switches[6]
set_location_assignment PIN_AB26 -to switches[7]
set_location_assignment PIN_AC25 -to switches[8]
set_location_assignment PIN_AB25 -to switches[9]
set_location_assignment PIN_AC24 -to switches[10]
set_location_assignment PIN_AB24 -to switches[11]
set_location_assignment PIN_AB23 -to switches[12]
set_location_assignment PIN_AA24 -to switches[13]
set_location_assignment PIN_AA23 -to switches[14]
set_location_assignment PIN_AA22 -to switches[15]
set_location_assignment PIN_Y24 -to switches[16]
set_location_assignment PIN_Y23 -to switches[17]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[0] 
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[7]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[8]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[9]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[10]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[11]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[12]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[13]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[14]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[15]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[16]
set_instance_assignment -name IO_STANDARD "2.5 V" -to switches[17]
